version: '3'

services:
  php.apache:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        user: webcomcafe
        uid: 1000
    image: php-7.0/apache
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.:/var/www/html'

